spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    password: Metalero2607$
    url: jdbc:postgresql://localhost:5433/companies
    username: jcharlie-prod
