spring:
  aplication:
    name: ms-client
  jpa:
    properties:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/test-db
    username: postgres
    password: Metalero2607
server:
  port: 8080
